### ISSUE TITLE
读取某个对象的OutOfService属性，返回nil

### ISSUE THREAD

**Issue by ltfred** [scopeccsky/bacnet#1]
```
data2, err := c.ReadProperty(ctx, device, bacip.ReadProperty{
	ObjectID: objID,
	Property: bacnet.PropertyIdentifier{
		Type: bacnet.OutOfService,
	},
})
```
如上，我想要读取OutOfService，返回nil。

**Comment by scopeccsky** [comment]
https://github.com/NubeDev/bacnet

**Comment by scopeccsky** [comment]
我现在没有可以调试的设备，不能做测试
最近有个新库，推荐使用测试，这个新库可能whois会有点问题， 其他的都很正常
https://github.com/NubeDev/bacnet

**Comment by itakyubi** [comment]
decoding不支持bool类型，加上下边两行就好了

`	case applicationTagBoolean:
		rv.Set(reflect.ValueOf(tag.Value != 0))
`

**Comment by scopeccsky** [comment]
#2 已经merge
